interactions:
  mushroom:
    - dialogue:
        text: Two colourful little mushrooms. Delicious? Or deadly?
  sign:
    - debug:
        text: Debugging...
    - dialogue:
        text: Welcome to Sunny Valley! If you're a newcomer, that is. Otherwise, good day I suppose...
    - dialogue:
        text: Thanks...?
  well:
    - dialogue:
        text: The town well is full to the brim with cool, fresh water.
  coin:
    - dialogue:
        text: Hey, there is a shiny coin here in the grass!
    - despawn:
        name: coin
    - debug: {}
    - state:
        key: has_coin
        action: true
    - debug: {}
    - dialogue:
        text: Nice!
  old_man:
    - when:
        conditions:
          - state:
              key: has_coin
              value: 0
        steps:
          - dialogue:
              text: I lost my coin somewhere in the grass. Can you help me find it?
        else:
          - dialogue:
              text: You found it! Thank you so much!
  forest_gravestone:
    - dialogue:
        text: The engraving on the gravestone has worn away. The stone is damp with moss and lichen.
  wheelbarrow:
    - dialogue:
        text: A well-used, tired old wheelbarrow. Who left that there?
triggers:
  test:
    - dialogue:
        text: Psst. Can you see me?
  door_home_inside_left:
    - teleport:
        to: door_home_outside_left
  door_home_outside_left:
    - teleport:
        to: door_home_inside_left
  door_home_inside_right:
    - teleport:
        to: door_home_outside_right
  door_home_outside_right:
    - teleport:
        to: door_home_inside_right
  door_inn_inside_left:
    - teleport:
        to: door_inn_outside_left
  door_inn_outside_left:
    - teleport:
        to: door_inn_inside_left
  door_inn_inside_right:
    - teleport:
        to: door_inn_outside_right
  door_inn_outside_right:
    - teleport:
        to: door_inn_inside_right
  door_house_inside_front:
    - teleport:
        to: door_house_outside_front
  door_house_outside_front:
    - teleport:
        to: door_house_inside_front
  door_house_inside_back:
    - teleport:
        to: door_house_outside_back
  door_house_outside_back:
    - teleport:
        to: door_house_inside_back
  door_farm_inside:
    - teleport:
        to: door_farm_outside
  door_farm_outside:
    - teleport:
        to: door_farm_inside
  door_shop_inside:
    - teleport:
        to: door_shop_outside
  door_shop_outside:
    - teleport:
        to: door_shop_inside
  door_dungeon_outside:
    - teleport:
        to: door_dungeon_inside
    - filter:
        name: night
    - music:
        name: forest
    - camera:
        zoom: 5
  door_dungeon_inside:
    - teleport:
        to: door_dungeon_outside
    - filter:
        name: day
    - music:
        name: town
    - camera:
        zoom: 4
  door_dungeon_lvl1_down:
    - teleport:
        to: door_dungeon_lvl2_up
  door_dungeon_lvl2_up:
    - teleport:
        to: door_dungeon_lvl1_down
  door_dungeon_lvl2_down:
    - teleport:
        to: door_dungeon_lvl3_up
  door_dungeon_lvl3_up:
    - teleport:
        to: door_dungeon_lvl2_down
  exit_forest:
    - filter:
        name: day
    - music:
        name: town
    - camera:
        zoom: 4
  enter_forest:
    - filter:
        name: night
    - music:
        name: forest
    - camera:
        zoom: 5
  door:
    - teleport:
        to: exit
  exit:
    - teleport:
        to: door

  